server:
  port: 8080
  servlet:
    context-path: /test
   
spring:

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: user-service
 
  datasource:
    url: jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true
   
    username: root
    password: Ab@12345
    driver-class-name: com.mysql.jdbc.Driver
